### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by explooosion**

### CODE REVIEW

**Comment by Gowee** [comment]
Still:
> Error: Unable to resolve action `szenius/set-timezone-action@v1.0`, repository not found

The ending `action` appears just to be a part of the repo name. So `szenius/set-timezone-action` -> `szenius/set-timezone`.

**Comment by JuanVqz** [comment]
this one works for me `szenius/set-timezone@v1.0`
Thank you, bro!

**Comment by leoarnold** [comment]
Ping @szenius

**Comment by szenius** [comment]
@explooosion Thank you for making the PR, and sorry for the late response! I was really swamped with life and only just checked out my inbox. Good day to you :-)

**Comment by szenius** [comment]
Also thanks to everyone else who tested the fix or pinged me!! @Gowee @JuanVqz @leoarnold

**Pull request merged**
